### ISSUE TITLE
Move string messages to resource file

### ISSUE THREAD

**Issue by larsk21** [kit-sdq/TimeSheetGenerator#51]
- move strings to i18n properties file
- access strings through ResourceBundle

*additional benefit*: possible to add translations later

**open questions**:
- [x] naming conventions for string keys (@gstuer)
- [x] where is the ResourceBundle loaded?
  - final static variable per class
  - central resource managing class
  - ...

**Comment by larsk21** [comment]
see bc45b843da84d0d24f0879907f41a8aaafa37637 as an example

**Comment by gstuer** [comment]
I propose the following scheme:
- The structure as seen in bc45b84 should be kept. In other words a central resource managing class with an easy-to-use interface consisting of just one static method is the cleanest way to implement the needed functionality, even though a such wide-ranging class should better not be completely static according to the object orientation paradigm. Therefore we should make this trade-off at this point.

- I would recommend a **hierarchically structured**, **lowercase** or **lowerCamelCase** (depending on if it is needed or not) name for the string keys. The name level separator should be a **dot** and the key should be followed by an **equality sign** "=". As top levels the following three could be used: 
  - `error` for every kind of exception or error. May be followed by a second level identifying the context, e.g. a class name, in which the error occurs. This gives us the possibility to shorten the last level identifier of an error.
  - `command` for commands and associated elements including descriptions, help-messages etc.
  - `file` for file extensions and their descriptions.
  - Any other important classes of elements needed?

**Comment by larsk21** [comment]
Could you give some guidelines for the translation process, i.e. when new keys are added to the root message bundle and have to be translated and added to the localized message bundles?

**Comment by gstuer** [comment]
Yes, of course!
Because of the size of the project and current number of developers working on the project on a regular basis, we should focus our style of working on **simplicity and convenience**.

Consequently, the following rules seem to fit our needs:
- The contributors just have to write their new/needed keys into the root message bundle when pushing their own commits to pull-request branches.
- If the root message bundle is edited and the pull-request is ready for review, translators for the different languages should be assigned to the PR and translate the new keys to every other bundle **before it will be merged into the master branch**.
- The message bundles should always be kept **up-to-date and consistent in the master branch**. (Maybe we should create a little tool for that?)
- In an ideal situation, we should **avoid changes to message bundles directly merged into the release branch**, in order to guarantee the consistency of the bundles.
