### ISSUE TITLE
Add vacation property to entry element in month.json

### ISSUE THREAD

**Issue by gstuer** [kit-sdq/TimeSheetGenerator#71]
The vacation should be an own entry in the latex document table and therefore we need an optional vacation boolean property for the entry elements.

**Attention**: The parser(s), calculation and json schema also needs to be changed in order to calculate the correct working time and vacation time.

**Comment by larsk21** [comment]
### Couple of questions

(for the current progress see the branch `PR_VacationEntries`; if you use the compare function, remember that the base branch is `PR_JacksonJson` not `master`)

*(assumptions made in the current code are written in italic)*

- Should there be entries for sick days or absence for other reasons as well? *(assumption: no)*
- Since you can specify start and end time for vacation days, can there be a pause as well? *(assumption: no)*
- What is the maximum time of vacation for a single day? *(assumption: none)*
- Can there be work time and vacation time on the same day? *(assumption: yes)*
- Do the vacation times have to obey the working day restrictions as well? *(assumption: yes)*
- How is a vacation entry shown in the generated LaTeX document? Is the total time for the day shown or a shorthand for vacation instead? *(assumption: shorthand for vacation and the total "working" time for the day, for example: "U 08:00" ["U" is short for the german word "Urlaub", meaning "vacation"])*

**Comment by gstuer** [comment]
I have addressed all of your questions to people who are able to answer them. As soon as I know the answers I will post them right here :)

**Comment by gstuer** [comment]
> * Should there be entries for sick days or absence for other reasons as well? _(assumption: no)_

No, there shouldn't. Our current users wouldn't use this feature and therefore it would not make sense implementing it. Furthermore, I'm apprehensive that this feature could make the process of filling in the json more complicated.

> * Since you can specify start and end time for vacation days, can there be a pause as well? _(assumption: no)_

No there cannot be a pause.

> * What is the maximum time of vacation for a single day? _(assumption: none)_

The maximum vacation time is just regulated by day time restrictions as far as I can judge.

> * Can there be work time and vacation time on the same day? _(assumption: yes)_

Yes, this is possible.

> * Do the vacation times have to obey the working day restrictions as well? _(assumption: yes)_

At this point I cannot completely resolve that question. For now I would prefer a solution that keeps the vacation times within the legal working time restrictions in order to avoid problems. In further consequence I am going to address this issue to a legal expert to resolve it.

> * How is a vacation entry shown in the generated LaTeX document? Is the total time for the day shown or a shorthand for vacation instead? _(assumption: shorthand for vacation and the total "working" time for the day, for example: "U 08:00" ["U" is short for the german word "Urlaub", meaning "vacation"])_

The **action field** can be filled by the users. They can fill in free text but I think we should give them some kind of guideline in order to make it simpler for the verifying instances (not in code but maybe in the README). **Date, begin and end** are filled as usual. **Pause** should be constant 00:00 (Any problems with this solution?). **The working time** is also calculated as usual but after the time string should be a U for "Urlaub". This could look like `08:30 U` or `08:30U`. I personally would prefer the solution with the space to make it more visible.
